### ISSUE TITLE
Save default scenario within the project data

### ISSUE THREAD

**Issue by sthiele** [ARB-Lab/CNApy#31]
Not sure yet how this is done best. 
In some sense the bounds on the models reaction represent itself a scenario. 
Should constraints from an default scenario would overwrite these bounds?

Example: in the model has reaction R the bounds -10>=,<=5
                in the scenario the bounds are set to       6>=,<=10.

I see two ways to interpret this situation and I'm not yet sure which to choose:
1. If i give both constraints there would be no solution. 
2. if the scenario replaces the models constraint there are solutions

**Comment by sthiele** [comment]
Hey @VonAlphaBisZulu @Paulocracy @axelvonkamp do you have an opinion on that?

**Comment by VonAlphaBisZulu** [comment]
My opinion: Default scenario should mean default bounds, anything else is confusing for first-timers. At most, if reactions are bound to a fixed value (e.g. 0) this value can be put into the reaction box to make it more obvious. I dislike the current practice in MATLAB-CNA-projects.

**Comment by sthiele** [comment]
How would be the workflow to save a new default scenario?

-> New projects default scenario is empty.
1. Set up a scenario.
2. Set current scenario as defaults scenario for this project.
3. Save project.

Or I think I would prefer to make step 2 and 3 just one step - Save project with current scenario!
