### ISSUE TITLE
Compute In/Out fluxes at a metabolite

### ISSUE THREAD

**Issue by sthiele** [ARB-Lab/CNApy#54]
I think this should be reimplemented in python. It looks like the glue code would be more than the current implementation.

**Comment by axelvonkamp** [comment]
I have just pushed a basic implementation of this feature. It can currently be used from the console, e.g. do an FBA with the ECC2comp model and on the console call:
cna.in_out_fluxes('g6p_c')

**Comment by sthiele** [comment]
You can now use this by right clicking on a metabolite.

https://user-images.githubusercontent.com/1641315/104617639-f83b2280-568b-11eb-8f3c-404180677a31.mp4
